### PR TITLE
Change iteritems() to items() to avoid "crash" when deleting a repository

### LINKED ISSUE #59: Deleting repositories does not work
In "Settings", if a collection repository is selected and the "Delete" button is pressed, the following error message appears:
error_message_iteritems
The reason for the error message is that this part of the code has not been updated to Python 3.
PR #58 fixes it for me. It is a simple fix - just change iteritems() to items() in line 113.

### PR DESCRIPTION
**Pull request by havatv**
Necessary for QGIS 3, since it uses Python 3.
Here is the error message that this PR addresses:
error_message_iteritems

The error message will appear if you try to delete a repository in "Settings".

Fixes #59.

### CODE REVIEW

**Comment by havatv** [comment]
@akbargumbira, @elpaso, it would have been nice if this trivial PR also had made it to 0.7.0. Is it possible to merge it and publish 0.8.0 soon?

**Comment by elpaso** [comment]
Sorry I missed it, can you plet also update metadata.txt and update version and changelog?

**Comment by havatv** [comment]
> Sorry I missed it, can you please also update metadata.txt and update version and changelog?

Will do.

**Comment by havatv** [comment]
@elpaso, I have given it a try. Could you check if everything is OK?

**Comment by elpaso** [comment]
Thank you! I'll make the zip and upload it on Monday.

**Pull request merged**
