### PR TITLE
[FEATURE] add support for gitlab and gogs repositories

### PR DESCRIPTION
**Pull request by slarosa**
This will also support git.osgeo.org/gogs repositories.

### CODE REVIEW

**Comment by slarosa** [comment]
hi @akbargumbira , please could you take a look at this PR.
I see the travis failure, but I can't understand why it is failing!

Thanks.

**Comment by akbargumbira** [comment]
hi @slarosa, thanks! I just had a quick look on the PR, for the gitlab_handler I will merge it this weekend and perhaps release it after fixing the unittest :) 

One thing is that, can you remove the GogsHandler commits to the giturlparse module? I prefer to have these changes being pushed to the upstream repository (https://github.com/FriendCode/giturlparse.py), so that they can have benefit of this and it won't be hard to update changes from upstream to this repository later

Cheers

**Comment by slarosa** [comment]
@akbargumbira wrote:
> hi @slarosa, thanks! I just had a quick look on the PR, for the gitlab_handler I will merge it this weekend and perhaps release it after fixing the unittest :)

great!

> One thing is that, can you remove the GogsHandler commits to the giturlparse module? I prefer to have these changes being pushed to the upstream repository (https://github.com/FriendCode/giturlparse.py), so that they can have benefit of this and it won't be hard to update changes from upstream to this repository later

sure, but that package is not maintained anymore, it doesn't?
I saw that it is a third party package so I thought to update it from this repo.
We (QGIS Italian group) created a gogs repository [0] to share some resources and GOGS handler is necessary for this reason.
No problem to issue a new PR to the upstream repository of ```giturlparse```, but I fear it will not be merged quickly :-(

Thanks.

[0] - https://git.osgeo.org/gogs/qgisitalia/QGIS-Italia-Risorse

**Comment by akbargumbira** [comment]
> sure, but that package is not maintained anymore, it doesn't?
> I saw that it is a third party package so I thought to update it from this repo.
> We (QGIS Italian group) created a gogs repository [0] to share some resources and GOGS handler is necessary for this reason.
> No problem to issue a new PR to the upstream repository of giturlparse, but I fear it will not be merged quickly :-(

Alright. Let's not remove those commits, but let's make a PR to their repo (it's up to them to merge it/not)

**Comment by slarosa** [comment]
@akbargumbira sorry for the noise, but I have been trying to understand if the travis failure depends from my changes. It seems be uncorrelated with the changes of this PR.
Also, I just issued a PR on https://github.com/FriendCode/giturlparse.py/pull/16

Thanks.

**Comment by slarosa** [comment]
Thanks @akbargumbira .

**Comment by akbargumbira** [comment]
@slarosa I just released a new version with this support. Thanks for your work!

**Pull request merged**
