### PR TITLE
Adding R script support

### LINKED ISSUE #57: Share aloso R scripts
Would it be possible to extend the plugin to share also R scripts for QGIS 3? 

Tricky part could be that now R Processing is a separated plugin and not a core part anymore

### PR DESCRIPTION
**Pull request by havatv**
Adds R script support by introducing ``resource_sharing/resource_handler/r_handler.py``

Had to move some code in ``resource_sharing/collection_manager.py`` to facilitate removal of installed scripts when removing collections. This should also make it possible to get Processing scripts removed, but I have not fixed that in this PR.
Changes version to ``0.9.0``.
Added some information to ``NOTES.rst`` about the R script support (mentioning the ``rscripts`` subdirectory).

R script support can be tested against the *QGIS Resources Sharing Repository* (https://github.com/qgis/QGIS-Resources). The collection has the name ``QGIS R script collection``, and the id is ``qgis_rscripts``.

Fixes #57.

Documentation update in #63.

### CODE REVIEW

**Comment by havatv** [comment]
> I trust you blindly :)

You should not!  I am known to make mistakes ... !:-)

**Comment by elpaso** [comment]
besides, we should move this repo under QGIS umbrella, and I'm not supposed to be the maintainer of this plugin forever  :)

Can I at least add you as co-maintainer in the plugin website so you can upload new packages of this plugin autonomously?

**Comment by havatv** [comment]
I definitely agree when it comes to moving it under the QGIS umbrella.  One alternative, and a possible first step for the second alternative, is be to add it as a separate repository under github/qgis (e.g. github/qgis/resourcesharing). Another alternative is to include it as a core plugin.
In the meantime, it is OK for me to be a co-maintainer.

**Comment by elpaso** [comment]
@havatv you should be a co-maintainer now, let me know if you need more permissions I can make you a staff member.

**Comment by havatv** [comment]
Hi again, @elpaso. I have now been able to test on Windows. It seems to work, so I have uploaded version 0.9.0 of the plugin to plugins.qgis.org.

**Comment by elpaso** [comment]
Thanks, I received the notification. @akbargumbira, can you give commit rights to @havatv so he can merge PRs?

**Comment by akbargumbira** [comment]
@elpaso hi, I've added @havatv as the collaborator. Thanks for all the work @havatv !

**Pull request merged**
